/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



#define       RCC_base_add         0x40021000
#define       APB2_offset          0x18
#define       PORTA_base_add       0x40010800
#define       PORTB_base_add       0x40010C00
#define       GPIO_CRL_offset      0x00
#define       GPIO_CRH_offset      0x04
#define       GPIO_ODR_offset      0x0C
#define       GPIO_IDR_offset      0x08



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	volatile uint32_t *clock_reg    =   (uint32_t*) (RCC_base_add + APB2_offset);

	volatile uint32_t *porta_mode_reg_low     =    (uint32_t*) (PORTA_base_add + GPIO_CRL_offset);
	volatile uint32_t *porta_mode_reg_high    =    (uint32_t*) (PORTA_base_add + GPIO_CRH_offset);
	volatile uint32_t *porta_input_reg        =    (uint32_t*) (PORTA_base_add + GPIO_IDR_offset);

	volatile uint32_t *portb_mode_reg_low     =    (uint32_t*) (PORTB_base_add + GPIO_CRL_offset);
	volatile uint32_t *portb_mode_reg_high    =    (uint32_t*) (PORTB_base_add + GPIO_CRH_offset);
	volatile uint32_t *portb_output_reg       =    (uint32_t*) (PORTB_base_add + GPIO_ODR_offset);


	*porta_mode_reg_low  = 0x88888888;  // All pins of PORTA sets as Input
	*porta_mode_reg_high = 0x88888888; 

	*portb_mode_reg_low  = 0x22222222;  // All pins of PORTB sets as Output
	*portb_mode_reg_high = 0x22222222;

	while(1){
		if(*porta_input_reg){
			*portb_output_reg = *porta_input_reg;
		}
	}
}
